# Generated by Django 2.2.6 on 2019-10-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20180528_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='num_of_attendees',
        ),
    ]
